config/routes.rb
Rails.application.routes.draw do
  resources :comments
  get 'about' => 'pages#info'
  get 'contact' => 'pages#contact'

  root 'pages#info'
  resources :family_members

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :family_member
end

app/models/family_member.rb
class FamilyMember < ActiveRecord::Base
  has_many :comments
  mount_uploader :picture, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_name, :body, :family_member_id)
    end
end

app/controllers/family_members_controller.rb
class FamilyMembersController < ApplicationController
  before_action :set_family_member, only: [:show, :edit, :update, :destroy]

  # GET /family_members
  # GET /family_members.json
  def index
    @family_members = FamilyMember.all
  end

  # GET /family_members/1
  # GET /family_members/1.json
  def show
  end

  # GET /family_members/new
  def new
    @family_member = FamilyMember.new
  end

  # GET /family_members/1/edit
  def edit
  end

  # POST /family_members
  # POST /family_members.json
  def create
    @family_member = FamilyMember.new(family_member_params)

    respond_to do |format|
      if @family_member.save
        format.html { redirect_to @family_member, notice: 'Family member was successfully created.' }
        format.json { render :show, status: :created, location: @family_member }
      else
        format.html { render :new }
        format.json { render json: @family_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /family_members/1
  # PATCH/PUT /family_members/1.json
  def update
    respond_to do |format|
      if @family_member.update(family_member_params)
        format.html { redirect_to @family_member, notice: 'Family member was successfully updated.' }
        format.json { render :show, status: :ok, location: @family_member }
      else
        format.html { render :edit }
        format.json { render json: @family_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /family_members/1
  # DELETE /family_members/1.json
  def destroy
    @family_member.destroy
    respond_to do |format|
      format.html { redirect_to family_members_url, notice: 'Family member was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_family_member
      @family_member = FamilyMember.find(params[:id])
      @comments = @family_member.comments.all
      @comment = @family_member.comments.build
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def family_member_params
      params.require(:family_member).permit(:name, :relationship, :age, :picture)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/family_members_helper.rb
module FamilyMembersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <%= f.hidden_field :family_member_id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Comments</h1>

<table>
  <thead>
    <tr>
      <th>User name&nbsp;&nbsp;</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_name %></td>
        <td><%= comment.body %>&nbsp;&nbsp;</td>
        <td><%= link_to 'Show', comment %>&nbsp;</td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %>&nbsp;</td>
        <td><%= link_to 'Delete', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @comment.user_name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Family member:</strong>
  <%= @comment.family_member_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/family_members/_form.html.erb
<%= form_for @family_member, :html => {:multipart => true} do |f| %>
  <% if @family_member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@family_member.errors.count, "error") %> prohibited this family_member from being saved:</h2>

      <ul>
      <% @family_member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :relationship %><br>
    <%= f.text_field :relationship %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/family_members/edit.html.erb
<h1>Editing Family Member</h1>

<%= render 'form' %>

<%= link_to 'Show', @family_member %> |
<%= link_to 'Back', family_members_path %>

app/views/family_members/index.html.erb
<html><body style="background-color:#F0F8FF"></body></html>

<h1>My Family</h1>

<br>

<% @family_members.in_groups_of(3) do |group| %>
  <div class="row">
    <% group.compact.each do |family_member| %>
      <div class="col-md-4">
        <%= image_tag family_member.picture_url, width: '100%' if family_member.picture.present?%>
        <h4><%= link_to family_member.name, family_member %></h4>
        <h5><%= family_member.relationship %>, <%= family_member.age %></h5>
        <br>
        <h4>Comments</h4>
        <% family_member.comments.each do |comment| %>
          <div>
            <strong><%= comment.user_name %></strong>
            <br />
            <p><%= comment.body %></p>
          </div>
        <% end %>
        <br><br>
      </div>
    <% end %>
  </div>
<% end %>

<br><br>

<%= link_to 'New Family member', new_family_member_path %>

app/views/family_members/new.html.erb
<h1>New Family Member</h1>

<%= render 'form' %>

<%= link_to 'Back', family_members_path %>

app/views/family_members/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-9">
    <%= image_tag(@family_member.picture_url, width: '100%') if @family_member.picture.present? %>
  </div>

  <div class="col-md-3">
    <p><b>Name: </b><%= @family_member.name %></p>
    <p><b>Relationship: </b><%= @family_member.relationship %></p>
    <p><b>Age: </b><%= @family_member.age %></p>
    <p>
      <%= link_to 'Edit', edit_family_member_path(@family_member) %> |
      <%= link_to 'Delete', @family_member, data: { confirm: 'Are you sure?' }, method: :delete %> |
      <%= link_to 'Back', family_members_path %>
    </p>
  </div>
</div>

<h3>Comments</h3>
<% @comments.each do |comment| %>
  <div>
    <strong><%= comment.user_name %></strong>
    <br />
    <p><%= comment.body %></p>
    <p><%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %></p>
  </div>
<% end %>
<%= render 'comments/form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Aboutme</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Vipin Goyal</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><a href="/about">About Me</a></li>
          <li><a href="/family_members">My Family</a></li>
          <li><a href="/contact">Contact Me</a></li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
      <%= yield %>
  </div>

  <footer>
    <div class="container">
      &copy; 2015 Vipin Goyal. All Rights Reserved.
    </div>
  </footer>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

</body>
</html>

app/views/pages/contact.html.erb
<html><body style="background-color:#F0F8FF"></body></html>

<h1>Contact Me</h1>

<br>

<h4>Just send me a message at <a href="mailto:goyalv@gmail.com?subject=Yo, Vipin!">goyalv@gmail.com</a>!</h4>

app/views/pages/info.html.erb
<html><body style="background-color:#F0F8FF"></body></html>
<h1>Vipin Goyal</h1>
<h4>Cofounder/Partner, Shipyard NYC (previously Founder/CEO of SideTour, acquired by Groupon)</h4>
Vipin was the Cofounder & CEO of SideTour, a marketplace of unique experiences, which was acquired by Groupon in the fall of 2013. After joining Groupon, in addition to managing the SideTour business, Vipin also led sales & business development for GrouponLive. Vipin's previous work experiences include Joost, MTV Networks and McKinsey & Company, and he has an AB in Economics and an MBA from Harvard. A few months ago, Vipin left Groupon to start working on a new venture with his two SideTour cofounders.
<p></p>
<br>
<a href="https://www.linkedin.com/in/vipingoyal">LinkedIn</a>&nbsp;&nbsp;|&nbsp;
<a href="https://twitter.com/vipingoyal">Twitter</a>&nbsp;&nbsp;|&nbsp;
<a href="https://www.facebook.com/vgoyal">Facebook</a>
<p></p>